using System.Text;

namespace Riddersholm.Money.Generators;

/// <summary>
/// Emits the currency table used inside <c>Riddersholm.Money</c> itself.
/// </summary>
/// <remarks>
/// <para>
/// The lookup is split in two on purpose. A sparse <c>switch</c> maps the packed code to a dense
/// <em>ordinal</em>; everything else is indexed by that ordinal. Scalar metadata is exposed as
/// <c>ReadOnlySpan&lt;byte&gt;</c> built from constant collection expressions, which the compiler lays
/// out as a blob in the assembly rather than an array on the heap — so reading a currency's decimal
/// digits allocates nothing and runs no static constructor.
/// </para>
/// <para>
/// That matters because rounding is on the hot path. Materialising a <c>CurrencyInfo</c> object just to
/// read one byte would allocate every currency's metadata the first time anyone rounded a <c>Money</c>.
/// </para>
/// </remarks>
internal static class CoreEmitter
{
    public static string Emit(IReadOnlyList<CurrencyDefinition> currencies)
    {
        StringBuilder source = new();

        source.Line("""
            // <auto-generated/>
            // Generated by Riddersholm.Money.Generators from an ISO 4217 definition file.
            // Do not edit: change eng/iso-4217.json instead, via tools/Riddersholm.Money.DataSync.
            #nullable enable

            // RS0016: these members are not tracked in PublicAPI.*.txt. The public surface here is a
            // pure function of the currency data file, so it is governed by reviewing that data diff
            // and by the generator's snapshot tests rather than by restating 166 members by hand.
            #pragma warning disable RS0016

            using System;

            namespace Riddersholm.Money;
            """).Line();

        EmitCurrencyConstants(source, currencies);
        EmitTable(source, currencies);

        return source.ToString();
    }

    private static void EmitCurrencyConstants(StringBuilder source, IReadOnlyList<CurrencyDefinition> currencies)
    {
        source.Line("public readonly partial record struct Currency");
        source.Line("{");

        foreach (CurrencyDefinition currency in currencies)
        {
            source.LineInvariant($"    /// <summary>{EscapeXml(currency.Name)} ({currency.Code}, ISO {currency.NumericCode}).</summary>");
            source.LineInvariant($"    public static Currency {currency.Code} => new({currency.Packed}u);");
            source.Line();
        }

        source.Line("}").Line();
    }

    private static void EmitTable(StringBuilder source, IReadOnlyList<CurrencyDefinition> currencies)
    {
        source.Line("/// <summary>Generated ISO 4217 metadata, indexed by a dense ordinal.</summary>");
        source.Line("internal static class CurrencyTable");
        source.Line("{");
        source.Line("    /// <summary>The number of currencies known at compile time.</summary>");
        source.LineInvariant($"    public const int Count = {currencies.Count};");
        source.Line();

        EmitOrdinalLookup(source, currencies);
        EmitByteSpan(source, "DecimalDigits", "ISO minor-unit digit counts", currencies, static c => c.DecimalDigits);
        EmitByteSpan(source, "CashDecimalDigits", "cash digit counts", currencies, static c => c.CashDecimalDigits);
        EmitByteSpan(source, "CashRoundingSteps", "cash rounding steps, in last-place units", currencies, static c => c.CashRoundingStep);

        EmitSwitch(source, "GetMinorUnitsPerMajor", "long", "minor units per major unit (0 when there is none)",
            currencies, static c => c.MinorUnitsPerMajor.ToString(System.Globalization.CultureInfo.InvariantCulture) + "L");
        EmitSwitch(source, "GetNumericCode", "short", "ISO numeric codes",
            currencies, static c => c.NumericCode.ToString(System.Globalization.CultureInfo.InvariantCulture));
        EmitSwitch(source, "GetPacked", "uint", "packed alphabetic codes",
            currencies, static c => c.Packed.ToString(System.Globalization.CultureInfo.InvariantCulture) + "u");
        EmitSwitch(source, "GetCode", "string", "ISO alphabetic codes",
            currencies, static c => Quote(c.Code));
        EmitSwitch(source, "GetName", "string", "English display names",
            currencies, static c => Quote(c.Name));
        EmitSwitch(source, "GetSymbol", "string", "currency symbols",
            currencies, static c => Quote(c.Symbol));

        source.Line("}");
    }

    private static void EmitOrdinalLookup(StringBuilder source, IReadOnlyList<CurrencyDefinition> currencies)
    {
        source.Line("""
                /// <summary>Maps a packed currency code to its ordinal, or returns <see langword="false"/>.</summary>
                public static bool TryGetOrdinal(uint packed, out int ordinal)
                {
                    switch (packed)
                    {
            """);

        for (int i = 0; i < currencies.Count; i++)
        {
            source.LineInvariant($"            case {currencies[i].Packed}u: ordinal = {i}; return true; // {currencies[i].Code}");
        }

        source.Line("""
                        default: ordinal = -1; return false;
                    }
                }
            """).Line();
    }

    private static void EmitByteSpan(
        StringBuilder source,
        string name,
        string summary,
        IReadOnlyList<CurrencyDefinition> currencies,
        Func<CurrencyDefinition, byte> selector)
    {
        source.LineInvariant($"    /// <summary>Per-ordinal {summary}, laid out as static data rather than a heap array.</summary>");
        source.LineInvariant($"    public static ReadOnlySpan<byte> {name} =>");
        source.Line("    [");

        // Wrapped so a currency-data change stays readable in a diff instead of being one huge line.
        for (int i = 0; i < currencies.Count; i += 16)
        {
            StringBuilder line = new("        ");
            for (int j = i; j < currencies.Count && j < i + 16; j++)
            {
                line.TextInvariant($"{selector(currencies[j])}, ");
            }

            source.Line(line.ToString().TrimEnd());
        }

        source.Line("    ];").Line();
    }

    private static void EmitSwitch(
        StringBuilder source,
        string name,
        string returnType,
        string summary,
        IReadOnlyList<CurrencyDefinition> currencies,
        Func<CurrencyDefinition, string> selector)
    {
        source.LineInvariant($"    /// <summary>Per-ordinal {summary}.</summary>");
        source.LineInvariant($"    public static {returnType} {name}(int ordinal) => ordinal switch");
        source.Line("    {");

        for (int i = 0; i < currencies.Count; i++)
        {
            source.LineInvariant($"        {i} => {selector(currencies[i])},");
        }

        source.Line("        _ => throw new ArgumentOutOfRangeException(nameof(ordinal)),");
        source.Line("    };").Line();
    }

    private static string Quote(string value) => "\"" + Escape(value) + "\"";

    /// <summary>Escapes a value for use inside a C# string literal.</summary>
    private static string Escape(string value) => value
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"");

    /// <summary>
    /// Escapes a value for use inside an XML documentation comment.
    /// </summary>
    /// <remarks>
    /// Two ISO currencies carry a bare ampersand — "São Tomé &amp; Príncipe Dobra" and "Trinidad
    /// &amp; Tobago Dollar" — which is not valid XML and breaks the documentation build.
    /// </remarks>
    private static string EscapeXml(string value) => value
        .Replace("&", "&amp;")
        .Replace("<", "&lt;")
        .Replace(">", "&gt;");
}
