using System.Text;

namespace Riddersholm.Money.Generators;

/// <summary>
/// Emits currency members for a <em>consuming</em> assembly.
/// </summary>
/// <remarks>
/// <para>
/// This is the reason the generator exists. The ISO table barely justifies a Roslyn component on its
/// own — it is a static list that changes about once a year, and a checked-in file would serve. What a
/// checked-in file cannot do is give a consumer's own currencies the same first-class treatment.
/// </para>
/// <para>
/// C# 14 static extension members let a consumer's assembly add <c>Currency.XBT</c> to a type it does
/// not own, so custom currencies read exactly like ISO ones. Metadata registration runs from a
/// <c>[ModuleInitializer]</c>: deterministic, reflection-free, and trim/AOT safe.
/// </para>
/// <para>
/// Because the packed representation carries the code itself, custom currencies need no shared index
/// space and no coordination with the ISO table. <c>Currency.FromCode("XBT")</c> already round-trips
/// through JSON and the database whether or not this generator ever ran.
/// </para>
/// </remarks>
internal static class ExtensionEmitter
{
    public static string Emit(
        string containerName,
        string containerNamespace,
        IReadOnlyList<CurrencyDefinition> currencies)
    {
        StringBuilder source = new();

        source.Line("""
            // <auto-generated/>
            // Generated by Riddersholm.Money.Generators from a currency definition file.
            #nullable enable

            using System.Runtime.CompilerServices;
            using Riddersholm.Money;
            """).Line();

        if (containerNamespace.Length > 0)
        {
            source.Line($"namespace {containerNamespace};").Line();
        }

        source.Line("/// <summary>Currencies defined by this assembly, surfaced as members of <see cref=\"Currency\"/>.</summary>");
        source.Line($"public static class {containerName}");
        source.Line("{");
        source.Line("    extension(Currency)");
        source.Line("    {");

        foreach (CurrencyDefinition currency in currencies)
        {
            source.Line($"        /// <summary>{EscapeXml(currency.Name)} ({currency.Code}).</summary>");
            source.Line($"        public static Currency {currency.Code} => Values.{currency.Code};");
            source.Line();
        }

        source.Line("    }").Line();

        // Resolving each code once beats re-packing it on every property read.
        source.Line("    private static class Values");
        source.Line("    {");

        foreach (CurrencyDefinition currency in currencies)
        {
            source.Line($"        internal static readonly Currency {currency.Code} = Currency.FromCode(\"{currency.Code}\");");
        }

        source.Line("    }").Line();

        source.Line("""
                /// <summary>
                /// Publishes metadata for these currencies before any of this assembly's code runs.
                /// A module initializer is used rather than reflection so registration survives
                /// trimming and NativeAOT.
                /// </summary>
                [ModuleInitializer]
                internal static void Register() => CurrencyRegistry.Register(
                [
            """);

        foreach (CurrencyDefinition currency in currencies)
        {
            source.Line("        new CurrencyInfo(");
            source.Line($"            code: \"{currency.Code}\",");
            source.Line($"            numericCode: {currency.NumericCode},");
            source.Line($"            englishName: \"{Escape(currency.Name)}\",");
            source.Line($"            symbol: \"{Escape(currency.Symbol)}\",");
            source.Line($"            decimalDigits: {currency.DecimalDigits},");
            source.Line($"            minorUnitsPerMajor: {currency.MinorUnitsPerMajor},");
            source.Line($"            cashDecimalDigits: {currency.CashDecimalDigits},");
            source.Line($"            cashRoundingStep: {currency.CashRoundingStep}),");
        }

        source.Line("    ]);");
        source.Line("}");

        return source.ToString();
    }

    /// <summary>Turns a file name such as <c>crypto-currencies.json</c> into <c>CryptoCurrencies</c>.</summary>
    public static string ToIdentifier(string fileName)
    {
        StringBuilder identifier = new();
        bool capitaliseNext = true;

        foreach (char c in fileName)
        {
            if (char.IsLetterOrDigit(c))
            {
                identifier.Append(capitaliseNext ? char.ToUpperInvariant(c) : c);
                capitaliseNext = false;
            }
            else
            {
                capitaliseNext = true;
            }
        }

        if (identifier.Length == 0 || char.IsDigit(identifier[0]))
        {
            identifier.Insert(0, "Currencies");
        }

        return identifier.ToString();
    }

    /// <summary>Escapes a value for use inside a C# string literal.</summary>
    private static string Escape(string value) => value
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"");

    /// <summary>
    /// Escapes a value for use inside an XML documentation comment. A bare ampersand is not valid XML,
    /// and two ISO currency names contain one.
    /// </summary>
    private static string EscapeXml(string value) => value
        .Replace("&", "&amp;")
        .Replace("<", "&lt;")
        .Replace(">", "&gt;");
}
