using System.Text.RegularExpressions;
using Xunit;

namespace Riddersholm.Money.Generators.Tests;

/// <summary>
/// Runs the generator over the real <c>eng/iso-4217.json</c> that ships, rather than over a fixture.
/// </summary>
/// <remarks>
/// This is the guard against a bad currency-data refresh. A snapshot of the whole generated file would
/// be enormous and would churn on every ISO amendment; asserting the table's <em>shape</em> and a set
/// of representative entries catches the failures that matter — a currency dropped, a precision
/// changed, a non-money code creeping in — without a 1,700-line expected file to re-approve.
/// </remarks>
public sealed partial class IsoCurrencyTableTests
{
    private static readonly string IsoJson = File.ReadAllText(
        Path.Combine(AppContext.BaseDirectory, "iso-4217.json"));

    private static readonly string Generated =
        GeneratorHarness.Run(IsoJson, emitCore: true).Source("Currency.Generated.g.cs")!;

    [Fact]
    public void The_shipped_data_generates_without_diagnostics() =>
        Assert.Empty(GeneratorHarness.Run(IsoJson, emitCore: true).DiagnosticIds);

    [Fact]
    public void The_table_holds_exactly_the_expected_number_of_currencies() =>
        Assert.Contains("public const int Count = 166;", Generated, StringComparison.Ordinal);

    [Fact]
    public void One_constant_is_emitted_per_currency() =>
        Assert.Equal(166, CurrencyConstant().Count(Generated));

    [Theory]
    [InlineData("DKK")]
    [InlineData("EUR")]
    [InlineData("USD")]
    [InlineData("JPY")]
    [InlineData("KWD")]
    [InlineData("MRU")]
    [InlineData("XXX")]
    [InlineData("XTS")]
    [InlineData("XAF")]
    [InlineData("XCG")]
    public void Representative_currencies_are_present(string code) =>
        Assert.Contains($"public static Currency {code} =>", Generated, StringComparison.Ordinal);

    [Theory]
    [InlineData("XAU")] // gold
    [InlineData("XAG")] // silver
    [InlineData("XDR")] // special drawing rights
    [InlineData("XUA")] // ADB unit of account
    [InlineData("XBA")] // European composite unit
    [InlineData("XAD")] // Arab accounting dinar
    [InlineData("DEM")] // withdrawn
    public void Metals_funds_and_withdrawn_codes_are_absent(string code) =>
        Assert.DoesNotContain($"public static Currency {code} =>", Generated, StringComparison.Ordinal);

    [Fact]
    public void XXX_occupies_the_reserved_zero_slot() =>
        Assert.Contains("public static Currency XXX => new(0u);", Generated, StringComparison.Ordinal);

    [Fact]
    public void The_fifth_minor_unit_currencies_keep_their_divisor()
    {
        // Regenerating from ISO alone would quietly reset these to 100 and make 1.37 MRU look payable.
        Assert.Contains("5L,", Generated, StringComparison.Ordinal);
        Assert.Contains("public static Currency MRU =>", Generated, StringComparison.Ordinal);
        Assert.Contains("public static Currency MGA =>", Generated, StringComparison.Ordinal);
    }

    [Fact]
    public void Every_emitted_constant_has_a_documentation_comment()
    {
        // The documentation build is warnings-as-errors, so an unescaped name would break it.
        int constants = CurrencyConstant().Count(Generated);
        int summaries = DocumentedConstant().Count(Generated);

        Assert.Equal(constants, summaries);
    }

    [Fact]
    public void The_generated_source_is_marked_auto_generated()
    {
        Assert.StartsWith("// <auto-generated/>", Generated.TrimStart('﻿'), StringComparison.Ordinal);
        Assert.Contains("#nullable enable", Generated, StringComparison.Ordinal);
    }

    [GeneratedRegex(@"public static Currency [A-Z]{3} => new\(\d+u\);")]
    private static partial Regex CurrencyConstant();

    [GeneratedRegex(@"/// <summary>[^<]*\([A-Z]{3}, ISO \d+\)\.</summary>\s*\r?\n\s*public static Currency")]
    private static partial Regex DocumentedConstant();
}
